server.port=8085
spring.application.name=SMLLOCAL-cida-web

## CONFIG BANCO POSTGRES
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/sml_cida
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=senhanormal123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

diretorio.base=classpath

jwt.private.key=${diretorio.base}:app.key
jwt.public.key=${diretorio.base}:app.pub
app.pasta-fotos=C:/sqliteDbs/fotos/
